### ISSUE TITLE
add back button and clear cache button

### ISSUE THREAD

**Issue by swyxio** [smol-ai/GodMode#110]

**Comment by ivanleomk** [comment]
Open to picking up this PR but just wanted to clarify a few things

- Does clear cache in this context just mean removing the current single sign on user? I
- How would the back button work in this case? (Eg. if a user is on the wrong pane then I assume just removing then adding the provider fixes this issue? )

**Comment by swyxio** [comment]
i think its more like remove cookies, and programmatically go back in page history

**Comment by swyxio** [comment]
implemented in #136
