### ISSUE TITLE
Always opens on Desktop 1

### ISSUE THREAD

**Issue by geelen** [smol-ai/GodMode#115]
I use multiple spaces/desktops on Mac, to separate out each project that I'm working on away from distractions. Sadly, whether I use the global shortcut or click the icon in the menu bar, it always first sends me to Desktop 1 before opening.

Right clicking the item in the menu bar doesn't do this, so it's something to do with opening the main window, but ideally it'd stay where I already am.

Neat idea for an app though!

**Comment by swyxio** [comment]
thanks for the report! i use multiple monitors every day, but not multiple spaces. i bet theres a simple solution for this one, but not tackling it just yet

**Comment by swyxio** [comment]
let us know if this is still an issue - i'm not super sensitive to it but udnerstand it can be a pain (i'm also a multiple monitor guy)
