### ISSUE TITLE
Behavior on Shortcut Key Change

### ISSUE THREAD

**Issue by kolinkorr839** [smol-ai/GodMode#120]
I am on version 0.0.17 on Mac and I noticed 2 things:

1. The shortcut (shift-command-g) does not close smolbar anymore (it used to be able to this). Now, I have to click the icon to close it.
2. I tried to click "Change Quick Open Shortcut" and the smolbar application just closes.

**Comment by swyxio** [comment]
thank you! going thru a bit of instability right now as we undergo a rewrite but will attend to this

**Comment by seanoliver** [comment]
Hey @kolinkorr839, can you confirm you're still having this issue with the latest build? I believe we resolved this in #170 but don't want to close prematurely.

**Comment by jagad89** [comment]
@seanoliver Don't know this is relevant or not. I am testing on windows computer. I am unable to switch/maximize particular window using Ctrl+Num shortcut. Do we have list of keyboard shortcuts to be tested on windows? Please share if its available. I will test and keep you posted. 
Let me know if I need to open new issue.

**Comment by jagad89** [comment]
I also experienced problem while logging on chatGPT. 
![image](https://github.com/smol-ai/GodMode/assets/4198516/5a6a4428-ae60-413e-9619-e0250fc702d7)
But after couple of restart application it started working.

**Comment by swyxio** [comment]
@jagad89 i've made a new label for windows issues: https://github.com/smol-ai/GodMode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AWindows would appreciate any help testing!
