### ISSUE TITLE
Moderate CPU Usage even if Application is not used

### ISSUE THREAD

**Issue by kolinkorr839** [smol-ai/GodMode#121]
I am not actively using the application and I noticed that it seems to be doing something in the background. See the CPU usage. I am not sure if this is expected or not.

I have enabled OpenAI, Bard, Bing and Claude 2. Also, I am on version 0.0.17 on Mac.

<img width="1645" alt="Screen Shot 2023-08-14 at 10 26 21 AM" src="https://github.com/smol-ai/menubar/assets/22241742/a2da3f2c-808e-4586-b25f-eac93deff0bb">

**Comment by swyxio** [comment]
i'm not sure either, as i initially was worried about that, but honestly i have not actually noticed any slowdown at all in daily usage. anyway, the whole code is open source, we're not doing anything funky other than loading the webviews. if there is heavy cpu usage its coming from the underlying chat apps

**Comment by swyxio** [comment]
can you please reopen if you see this as an issue with GodMode? (v1 and above)
