### ISSUE TITLE
GodMode: No ChatGPT Code Interpreter default

### ISSUE THREAD

**Issue by jacob1983** [smol-ai/GodMode#129]
**Description:** When launching GodMode, Code Interpreter is not chosen as default in ChatGPT 

**Steps to Reproduce:** Restart GodMode, Check dropdown next to GPT-4 in ChatGPT to see active model

**Expected Behavior:** GodMode should always default to CodeInterpreter (or possibly save and open last used model)

**Environment:** MacOS 13.4.1. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
thanks for filing - this one is a bit weird - 1) it seems to work for me, we hotlink directly to https://chat.openai.com/?model=gpt-4-code-interpreter', 2) the selection persistence is a recent new feature of ChatGPT.

cannot reproduce for now

**Comment by swyxio** [comment]
pls reopen if this persists but i am pretty sure this is not an issue with us
