### ISSUE TITLE
GodMode: Shortcut to access GodMode prompt window from the app

### ISSUE THREAD

**Issue by jacob1983** [smol-ai/GodMode#130]
**Description:** When GodMode is active and I have interacted with an LLM, I need to manually click on the GodMode prompt window "Enter a superprompt here" to make it active.

**Expected Behavior:** GodMode should have a keyboard shortcut making the GodMode prompt window instantly active.

**Environment:** MacOS 13.4.1. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
yeah agree. easy to do, i'll add this now.
