### ISSUE TITLE
GodMode doesn't hide on global shortcut

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/GodMode#131]
**Description:** GodMode window does not hide upon hitting the global shortcut when the window is open.

**Steps to Reproduce:**
1. Launch GodMode with global shortcut (CMD+Shift+G).
2. Use the global shortcut again (CMD+Shift+G)

**Expected Behavior:** GodMode becomes hidden
**Actual Behavior:** Godmode window stays open

**Environment:** macOS 13.4. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
we understand and agree - not a high pri thing since this is now meant to be a persistent app, but will take a PR for it if you want to take a stab
