### ISSUE TITLE
GodMode extremely slow opening time after close (and disabled global shortcut)

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/GodMode#133]
**Description:** After closing the window, hitting the global shortcut (CMD+Shift+G) no longer opens the window. Furthermore, reopening it manually by clicking it in the dock will restart the whole app and it takes ~5 seconds for all the components to load and become responsive.

**Steps to Reproduce:**
1. Close the window (CMD+W or click the red cross)
2. Try to use the global shortcut (CMD+Shift+G) -> Fails
3. Open manually (clicking icon in dock or double-clicking the application) -> app takes 5 seconds to restart

**Expected behavior:**
Hitting the global shortcut will show/hide the window as long as the app is running. Closing the window will simply hide it, and reopening it will have zero startup time.

**Environment:** macOS 13.4. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
agree and can replicate. great issue, great call out, thank you. i think the fix is easy, am on it

**Comment by swyxio** [comment]
unfortunately the fix i had i n mind (see commit above) did not work and i'm not sure why. if you see how to fix it, PR welcome.

**Comment by seanoliver** [comment]
Check out #141 I think this fixes it.
