### ISSUE TITLE
GodMode: App is active in dock and app-switcher

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/GodMode#134]
**Description:** GodMode is visible in the dock and app-switcher, which makes it very uncomfortable to tab between two applications without accidentally opening GodMode. For example, people often cmd+tab between an IDE and a browser as they work, and use GodMode in between. Having it be an app makes it unusable and barely different from having a couple LLMs open side-by-side in a browser tab.

**Steps to Reproduce**: Launch GodMode
**Expected behavior:** Will show/hide on pressing the global shortcut but will not be active in the dock or the app switcher (CMD+Tab).

Environment: macOS 13.4. GodMode (1.0.0-beta.0)

**Comment by swyxio** [comment]
> For example, people often cmd+tab between an IDE and a browser as they work, and use GodMode in between. 

so technically you can use the quick open shortcut (defaults to cmd+shift+g) and that makes it easy to access godmode from wherever

however,

> Expected behavior: Will show/hide on pressing the global shortcut but will not be active in the dock or the app switcher (CMD+Tab).

this is a smart solution. would happily take a PR for this, i am not exactly sure how we would make it happen
