### ISSUE TITLE
GodMode: Perplexity doesn't allow login. 

### ISSUE THREAD

**Issue by lgandecki** [smol-ai/GodMode#140]
This is what I see through GodMode: 
<img width="2036" alt="CleanShot 2023-08-18 at 16 55 49@2x" src="https://github.com/smol-ai/GodMode/assets/4002543/ce37697c-ad4a-419d-9c8f-d70ceb5f021e">
but it should look like this:

<img width="591" alt="CleanShot 2023-08-18 at 16 57 13@2x" src="https://github.com/smol-ai/GodMode/assets/4002543/2cfd940d-88fa-4408-9e0e-ccc2b47ff21d">

Any chance to reuse the cookies from the menubar? I was logged in to all the providers there. Sadly, perplexity is my favorite one, so I won't be able to switch to the new version (which I love the idea of!) without it.. 

Also - am I the only one with this problem?

thanks!

**Comment by swyxio** [comment]
youre not the only one - #113  - perplexity is a bit weird because once you are logged in to Google, it tries to auto log you in and sometimes it fails. when that happens, just reload, and it'll eventually load.

**Comment by swyxio** [comment]
closing for now bc its a known issue that solves itself, lmk/reopen if theres something we can do on our end

**Comment by lgandecki** [comment]
Thanks! Works like a charm. Love the new version. Thank you guys so much for this :)
