### ISSUE TITLE
URLs should open in system browser

### ISSUE THREAD

**Issue by g000m** [smol-ai/GodMode#149]
Current Behavior: Clicking links within GodMode opens the links within the Electron application itself.
Desired Behavior: Links should be opened by the system's default web browser.

I've never worked on an electron app, but Bard suggests the following as a fix. 

"This feature can be implemented by registering a window open handler on the application's BrowserWindow. The window open handler can be used to intercept links that are clicked by the user and open them in the system browser instead."
```
import { shell } from "electron";

const mainWindow = new BrowserWindow();

mainWindow.webContents.on('new-window', function(event, url) {
  event.preventDefault();
  shell.openExternal(url);
});
```

**Comment by swyxio** [comment]
yeah we should offer that option. i'm worried about opening ALL links in the system browser, but we can add the filters later

**Comment by codingnninja** [comment]
> this is better https://stackoverflow.com/questions/31749625/make-a-link-from-electron-open-in-browser

I am currently working on this. 

Quick one, I just fixed dependency conflicts while installing it, so I want to know if I should make PR before fixing the actual issue or I should ignore the dependency conflicts entirely and focus on fixing the main issue?

**Comment by swyxio** [comment]
@codingnninja ignore the dep conflicts, i am fixing in #180 thanks!

**Comment by codingnninja** [comment]
@swyxio I have fixed it but I am a bit confused by the contribution guideline. I forked the repo and pull the forked version but the guideline suggests I should pull from the main repo.

I could have followed the guideline but it seems incomplete. Please I need your input on the expected way before I do it my way. 

Thanks.

**Comment by swyxio** [comment]
@codingnninja the contribution docs are a bit out of date unfortunately. you did a great job!
