### ISSUE TITLE
[Looking for Contributors] add Ollama support

### ISSUE THREAD

**Issue by swyxio** [smol-ai/GodMode#153]
https://github.com/jmorganca/ollama + https://github.com/rtcfirefly/ollama-ui

should be similar to the oobabooga setup. remember to update docs

**Comment by ishaan-jaff** [comment]
Hi @swyxio  I’m the maintainer of LiteLLM - we allow you to create a proxy server to call 100+ LLMs, and I think it can solve your problem (I'd love your feedback if it does not)

Try it here: https://docs.litellm.ai/docs/proxy_server

## Using LiteLLM Proxy Server
```python
import openai
openai.api_base = "http://0.0.0.0:8000/" # proxy url
print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```

## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```


Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

**Comment by itsbrex** [comment]
@ishaan-jaff I've been talking to Krrish a bit on LinkedIn and told him I still hadn't gotten around to checking out liteLLM yet and and here you are coming with an interesting solution for GodMode.

I can see liteLLM being massively helpful here and a lot of other places. Emailing you now. 🤙

**Comment by swyxio** [comment]
i dont appreciate issue spam - we need a UI.
