### ISSUE TITLE
On french keyboards it doesn't work

### ISSUE THREAD

**Issue by merwanehamadi** [smol-ai/GodMode#158]
Put your keyboard in french. Then try CMD + 1.
It doesn't work.
Probably other keybooards too

**Comment by swyxio** [comment]
use english!! lol

on a serious note, would love help. probably just a simple config in electron somewhere. if anyone sees this, PR welcome

**Comment by swyxio** [comment]
@merwanehamadi , @mwyywm may have fixed this for you. pls try in our latest (beta 7 and above) release!

**Comment by merwanehamadi** [comment]
thanks will check
