### ISSUE TITLE
GodMode: Unable to install and run beta-1 / beta-2 on Intel based mac

### ISSUE THREAD

**Issue by anugrahsinghal** [smol-ai/GodMode#163]
I have a MacBook Pro with an Intel processor. 
I was able to successfully install and run the beta-0 release of GodMode, but later beta versions (beta-1 and 2) fail to start up on my machine.

The smol-menubar releases(v0.0.17) seem to work without issue. It appears to be a problem specific to the main GodMode app in releases after beta-1.

Steps to reproduce:

- Install GodMode beta-0 - runs successfully
- Install GodMode beta-1/2 - app fails to launch

I've tried:

- Deleting previous GodMode installs before installing new version
- Installing GodMode-beta-1/2 after installing beta-0.
- Deleting previous menubar installs before installing new version

<img width="501" alt="SCR-20230821-mffv" src="https://github.com/smol-ai/GodMode/assets/18058884/6ac6dc88-e6f9-4db6-b5fc-72f8188686ef">
<img width="303" alt="SCR-20230821-mfkb" src="https://github.com/smol-ai/GodMode/assets/18058884/8f882b11-4877-407f-9816-f5d65f5f2882">

I used these release files:
https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.2/GodMode.1.0.0-beta.2.dmg
https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.1/GodMode.1.0.0-beta.1.dmg

**Comment by bsharper** [comment]
Can confirm. When looking at the .app in the release dmg (GodMode.1.0.0-beta.2.dmg), it looks like the binary under the MacOS folder is for `arm64`. 

```
❯ file GodMode
GodMode: Mach-O 64-bit executable arm64
```

It could be this error in `package.json` under the package build target info for macOS:
```
                         "arch": [
					"arm64",
					"'universal",
					"x64"
				]
```

("universal" has a single quote at the beginning)

**Comment by ericbernhard** [comment]
Same for me.  2019 Intel based Mac

**Comment by anugrahsinghal** [comment]
Update: just tried beta-3, still have the same issue even after the #162 fix.

**Comment by DannyMac180** [comment]
Same - still the same issue after trying with beta-3

**Comment by weavingtan** [comment]
Same for me,macOS Big Sur version 11.5.1

**Comment by swyxio** [comment]
thanks - if anyone can knows Electron enough to figure out the build process let me know!

**Comment by seanoliver** [comment]
Hey @anugrahsinghal (and all) can you try installing the universal build: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.3/GodMode-1.0.0-beta.3-universal.dmg

I was just able to get this running on my 2017 MacBook Pro w/ Intel. LMK if this version works for you!

**Comment by tayiorbeii** [comment]
@seanoliver Working on my 2019 Intel Mac!

**Comment by anugrahsinghal** [comment]
Hey @seanoliver 
Can confirm that the universal build works on my Intel Mac too.

**Comment by alfonmga** [comment]
> Hey @anugrahsinghal (and all) can you try installing the universal build: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.3/GodMode-1.0.0-beta.3-universal.dmg
> 
> I was just able to get this running on my 2017 MacBook Pro w/ Intel. LMK if this version works for you!



> Hey @anugrahsinghal (and all) can you try installing the universal build: https://github.com/smol-ai/GodMode/releases/download/v1.0.0-beta.3/GodMode-1.0.0-beta.3-universal.dmg
> 
> I was just able to get this running on my 2017 MacBook Pro w/ Intel. LMK if this version works for you!


@seanoliver Thanks for the release. Would you be able to do the same for the newest version `v1.0.0-beta.4`? There's an annoying bug (#168) that I would like to get rid of. Cheers, man

**Comment by deepakmca05** [comment]
Can't run the universal build as the macbook complains of it not being verifiable.
