### ISSUE TITLE
Missing GodMode icon in menubar

### ISSUE THREAD

**Issue by ankushagarwal** [smol-ai/GodMode#168]
Hi,

I am on a M2 Macbook Air and Installed GodMode using the [releases page](https://github.com/smol-ai/GodMode/releases/tag/v1.0.0-beta.2) GodMode.1.0.0-beta.2arm64.pkg. Its up and running, but I don't see the top-right menu icon in my macos menu bar.

This is missing: ![image](https://github.com/smol-ai/GodMode/assets/796949/e86da01b-fe29-49e2-a63f-1a2aaaeeb15f)

Not sure if this is expected or not.

I have checked that none of the menu bar items are hidden.

**Comment by swyxio** [comment]
we definitely de emphasized it but i think @seanoliver might wanna fix

**Comment by ankushagarwal** [comment]
I am not sure if this is related, but I cannot "Quit" the GodMode app. This maybe intentional, but when I try to Quit it simply hides in the background:
![image](https://github.com/smol-ai/GodMode/assets/796949/1afee76b-7c7f-4235-a4fe-f1902c25b122)

I have to jump into the Activity Monitor and "Force kill" all the godmode processes to quit it.
![image](https://github.com/smol-ai/GodMode/assets/796949/57a4ae61-f3b0-465e-bfdc-0fb7fa94bc82)

**Comment by seanoliver** [comment]
@ankushagarwal Thanks for flagging this! It's not related to the menubar icon issue, but it is a separate and very annoying bug. We have a hotfix out to resolve it in https://github.com/smol-ai/GodMode/pull/170 which should hopefully get merged shortly!

**Comment by ankushagarwal** [comment]
Thanks, @seanoliver!

**Comment by swyxio** [comment]
fix in #170
