### ISSUE TITLE
Ctrl+Shift+A (reset all) does not work on Windows 11

### ISSUE THREAD

**Issue by martypenner** [smol-ai/GodMode#172]
There is no way that I'm aware to refresh / reset all panels. This is on the latest build as of today.

**Comment by swyxio** [comment]
we do have this thing at the bottom right but thanks! might need some more keyboard testing. let me know if you can run it locally and PR a fix for the keyboard shortcut

<img width="405" alt="image" src="https://github.com/smol-ai/GodMode/assets/6764957/c273a32d-075f-4464-bd48-33c1155c6ea5">

**Comment by martypenner** [comment]
When I tested that, it also reset the chosen providers, which I didn't want to do. I'm hoping to have some time next week to see if I can resolve this and put up the PR.

**Comment by swyxio** [comment]
thank you!
