### ISSUE TITLE
Google component sign in flashes the username text box

### ISSUE THREAD

**Issue by grantsayer** [smol-ai/GodMode#176]
Unable to login as only see the 'Next' blue button and no active text box for the username.
If refresh then the input text box flashes but disappears a moment later

![image](https://github.com/smol-ai/GodMode/assets/148578/33762880-2107-4c49-9aec-9885178b7b32)
![image](https://github.com/smol-ai/GodMode/assets/148578/f4bf7fe8-ccf0-4e10-9f2f-b34a5aa99d74)

**Comment by swyxio** [comment]
very strange. try refreshing (cmd+R), or resizing. i have literlaly never seen this error before!

**Comment by chrishrtmn** [comment]
![Screenshot 2023-08-22 at 4 54 02 PM](https://github.com/smol-ai/GodMode/assets/226349/67ded4bf-21a0-46b6-ba58-fb6288a22b14)

I'm facing a similar issue - unable to view sign in fields and unable to click Next for Google for Bard. 

I'm on GodMode-1.0.0-beta.3-universal.

**Comment by swyxio** [comment]
@chrishrtmn  very sorry about that. never experienced in months of testing. can you try loggign into Claude first?

**Comment by swyxio** [comment]
consolidating to #11
