### ISSUE TITLE
Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.

### ISSUE THREAD

**Issue by ruuuuuuuuuuuuuuuuuuuaaaaaaaaa** [smol-ai/GodMode#177]
On Windows, once built, and you try to enter a prompt I get: 

Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.

I will note that I had to force the npm install as nearly every package was complaining.

**Comment by swyxio** [comment]
we've updated the deps #180 so the complaints stop

the error is a very common one and unfortunately an electron issue. it usually means that one of the pages isn't in the right state. can you screenshot the app here when before you enter the prompt? and make sure you're logged in to every one of the open apps

**Comment by swyxio** [comment]
please let me know if this issue persists in the latest release, and record a video of what exactly happens!

**Comment by lpetrov** [comment]
```
Error occurred in handler for 'GUEST_VIEW_MANAGER_CALL': Error: ERR_ABORTED (-3) loading 'https://www.google.com/'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:78838)
    at WebContents.navigationListener (node:electron/js2c/browser_init:2:79118)
    at WebContents.emit (node:events:530:35) {
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'https://www.google.com/'
}
```

Still happening on latest stable `35.1.5`.
