### ISSUE TITLE
NPN Install on Windows 10 getting the error message 

### ISSUE THREAD

**Issue by VenkataSRT** [smol-ai/GodMode#178]
While i am at the NPN Install on Window 10 - getting the error message 

"63 error Fix the upstream dependency conflict, or retry
63 error this command with --force or --legacy-peer-deps
63 error to accept an incorrect (and potentially broken) dependency resolution."

Up on checking Website - https://weekendprojects.dev/posts/resolved-npm-error-fix-the-upstream-dependency-conflict/

npm install --save --legacy-peer-deps

Resolved the issue.

**Comment by swyxio** [comment]
thanks!
