### ISSUE TITLE
Error occurred in handler for 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.

### ISSUE THREAD

**Issue by VenkataSRT** [smol-ai/GodMode#179]
I am on Windows 10 , it is giving the following error message

"Error occurred in handler for 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error."

![image](https://github.com/smol-ai/GodMode/assets/41136555/8e733f90-ae88-432b-bdbc-c3a68523468d)

**Comment by swyxio** [comment]
related to #175
