### ISSUE TITLE
Pasting password into Google login gets repeated multiple times

### ISSUE THREAD

**Issue by tayiorbeii** [smol-ai/GodMode#185]
On 1.0.0-beta 3 (Intel Mac), I went to log into my Google account in the ChatGPT tab and found that pasting password into Google Login for ChatGPT repeats the pasted text multiple times (either 4 or 5 or 6, I already forgot 😅)

**Comment by swyxio** [comment]
hmmm. havent experienced this one. type it in for now but i'm not sure why the paste would be repeated!

**Comment by swyxio** [comment]
moving this into #11
