### ISSUE TITLE
Bard custom provider CSS cuts off account switching bar

### ISSUE THREAD

**Issue by tayiorbeii** [smol-ai/GodMode#186]
After logging into ChatGPT with my Google Workspace account, I found it was picked up by the services in the other tabs (i.e. they showed a "Continue as..." that allowed me to login which was nice!

However, my Bard account is associated with my personal Gmail, and it seems that GodMode has cut off the top navbar that would allow for me to switch my Google account as seen in these screenshots:

Screenshot inside GodMode:
<img width="1637" alt="image" src="https://github.com/smol-ai/GodMode/assets/2262858/8116f90a-f6cd-4712-8912-3dfcc949199e">

Screenshot from Chrome:
<img width="1000" alt="image" src="https://github.com/smol-ai/GodMode/assets/2262858/05a9c3da-b07e-4126-a3bb-8d2ea901a3b1">

**Comment by swyxio** [comment]
@tayiorbeii ah that is due to some custom css we made to hide it to save vertical space. https://github.com/smol-ai/GodMode/blob/83bc6ddee70ede4c98a653c6920272ff394e0346/src/providers/bard.js#L49 welcome to make a PR to tweak the overall Bard css!

**Comment by swyxio** [comment]
i addressed in commit 7514d52..072a81b
