### ISSUE TITLE
[Request] possible options to add please

### ISSUE THREAD

**Issue by zono50** [smol-ai/GodMode#192]
I had a few ideas for things that would make it even better. My number 1 would be to be able to push the enter key instead of having to use the mouse. The second one would be to be able to use custom llms like quivr or privategpt, things like that.

**Comment by swyxio** [comment]
you can use cmd+enter to submit instead of using the mouse!

**Comment by zono50** [comment]
> you can use cmd+enter to submit instead of using the mouse!

awesome, thanks for the tip.
