### ISSUE TITLE
Unable to login at Google.

### ISSUE THREAD

**Issue by jeffara** [smol-ai/GodMode#201]
Hi guys,

I'm trying to login to Google Bard, but it seems that there is something happening with the way the browser is starting, because it says it may be not secure, and then I can't login. 

I'm attaching some images about the model of my computer (MacBook pro) and auxiliary screenshots of the problem, as well as a video to demonstrate what's happening.

https://github.com/smol-ai/GodMode/assets/15833879/9def6e5f-59bd-4e94-ae31-bc7d7e81eb80

![image](https://github.com/smol-ai/GodMode/assets/15833879/4ba555a1-619a-46d9-b7dc-261a497424ea)

![image](https://github.com/smol-ai/GodMode/assets/15833879/c9ca3ed2-eff1-4a72-abb9-30cac628b112)

Can anybody tell me if there is something I could do to surpass this?

Many thanks!

**Comment by richardstevenhack** [comment]
Same problem. I just launched GodMode and it came up. I signed in to Google for ChatGPT, no problem. 

However, when I click on the Bard tab and try to sign in, it wants me to create a new account. I already have my Google account open, and the proof is that I can access Bard from my Firefox browser tab where I already have Bard open. It does not show me the sign-in prompt at the top, either - that space is blank.

I did not, however, get any message about the browser being insecure.

I am able to sign in to Bing with no problem. Also I could use Perplexity via the one-time sign-in approach (I don't pay the $20 subscription.)  I am able to log in to Claude with the same email mechanism. I did not try Poe as I don't use that one yet.

I would like to get Bard working.

**Comment by richardstevenhack** [comment]
I should mention I'm running the AppImage for the previous release since I couldn't find one for the current release. The AppImage seems to run fine except for the Bard issue.

I am also running on openSUSE Leap 15.4 Linux if that helps.

**Comment by jakkaas** [comment]
Same here. I am using windows. Not able to use any google login. Browser not supported. I don't have Claude account on google, so also cannot use that.

**Comment by alexclaydon** [comment]
Same for me - identical error message.  Ventura 13.5.1, M1 Pro.

**Comment by lordboun** [comment]
je rencontre également le même problème pour me connecter via toute les autres hormis chatgpt alors qu'il est fait mention du faites que si l'on ce connecte a chat gpt toutes les comptes utilisant le même mails seront automatiquement connecter (je suis sur window )

**Comment by Irving199703** [comment]
same problem.

**Comment by swyxio** [comment]
thanks for the reports guys. i cant reproduce this yet but obviously its a huge problem. please let me know if anyone can run this in development mode and figure out the issue.

**Comment by richardstevenhack** [comment]
Uninstalled the previous version AppImage and installed the current version. Same issue. The Bard column comes up with the explanatory page and the option to Sign In. Clicking that opens the sign in page which has the options "Create New Account" and "Next" with the prompt "Enter Your Name" but there is no place to enter the name.

Clicking CTRL+2 at that point produces a larger version of the sign-in page, still no place to enter the name.

The URL at the top of that page shows this:
`https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fbard.google.com%2Fsignin%3Fcontinue%3Dhttps%3A%2F%2Fbard.google.com%2F&followup=https%3A%2F%2Fbard.google.com%2Fsignin%3Fcontinue%3Dhttps%3A%2F%2Fbard.google.com%2F&ifkv=AXo7B7Uc-0NR2TysttJZ7Rnmkv51XbqIrnlD-DDEZ-O41ZoJnv0qVTrlBMtDBQPuw1kaTxi1M3SqPg&passive=1209600&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S1392945581%3A1693329357913748`

If that helps.

Trying to edit that URL does not work.

The various CTRL functions at the top seem to work fine, moving back to the start up page or forward to the sign-in page, but no change to the lack of a place to enter one's email address.

I was able to login to all the rest of the AIs including Poe which I hadn't tried before.

**Comment by geeknik** [comment]
1. Visit https://bard.google.com/
2. F12 for console
3. Session: Application → Cookies → Copy the value of `__Secure-1PSID` cookie.
4. Don't share the value of `__Secure-1PSID`with anyone but that is how you auth with Bard. 👍🏻

**Comment by jeffara** [comment]
@geeknik , and how did you open the console on GodMode? I've tried to open it using Macbook and found now way to do this to inject the cookie.

**Comment by geeknik** [comment]
You have to grab the cookie value from Chrome or Firefox. Then you'll have to edit wherever GodMode handles the authentication for Bard so it uses this cookie value. 🤙🏻

**Comment by richardstevenhack** [comment]
@geeknik I agree with Jeffara. I was able to find the cookie in Firefox by going to the main Bard site, clicking F12 to open the console, clicking the Storage tab, expanding the Cookies section, and selecting https://bard.google.com, then expanding the "Name" column so as to see the _Secure-1PSID row, clicking on that shows the Data value in the far right which can be copied.

However, I see no way to use that to influence what GodMode is doing. We can't open a console in GodMode as far as I can tell.  And I can't see way to get to the authentication mechanism GodMode is using.

**Comment by swyxio** [comment]
goes without saying but if anyone has any ideas on how to improve either the debugging or root cause, please open a PR! need all the help i can get on this stuff

**Comment by swyxio** [comment]
on reflection i think this broke when @codingnninja enabled this thing https://github.com/smol-ai/GodMode/pull/196 which is exactly what i feared. i think what we will do is whitelist the SSO login domains for google so that it does not open in your primary browser.

**Comment by swyxio** [comment]
i also found this which... sneaky, Google https://www.reddit.com/r/electronjs/comments/eiy2sf/google_blocking_log_in_from_electron_apps/

**Comment by swyxio** [comment]
ok folks, could you try in v1 beta 6 please : https://github.com/smol-ai/GodMode/releases/tag/v1.0.0-beta.6

and reopen if any issues!

**Comment by altryne** [comment]
> ok folks, could you try in v1 beta 6 please : https://github.com/smol-ai/GodMode/releases/tag/v1.0.0-beta.6
> 
> and reopen if any issues!

Didn't work for me on the new Beta, via OpenAI, the above trick worked, Anthropic opened a new window, which allowed me to login, then everything else already had my google login and allowed me to just 'click' the email and continue

**Comment by swyxio** [comment]
thanks @richardstevenhack  - perplexity has occasional issues because of they way they have implemented their login, but usually it goes away once you refresh (cmd+shift+A)

**Comment by richardstevenhack** [comment]
CTRL-Shift-A has absolutely no effect on my system.

**Comment by jeffara** [comment]
> Well, now the problem has increased. I can sign in to Bard, but I still get the blank page with only the headings and buttons which are nonresponsive
> 
> And now I get the same from Perplixity that I had with Bard originally, i.e., I can't sign in. I get the "Welcome - Sign up or sign in" message prompt, but there is no response to clicking it. Trying to log in from CTRL-5 gives me the same thing.
> 
> Here is a screenshot of my current situation with all others logged in: ![Screenshot_20230905_132354](https://user-images.githubusercontent.com/44449170/265817858-f7850cfc-9e9c-421d-a7af-887c6b69e166.png)

I have the same problem.

**Comment by kianwoon** [comment]
I've come across a helpful trick that might save us from the common browser/app security alerts we've been facing. If you sign in to Anthropic claude 2 using your Gmail account first, you can then access Poe or Google Bard/Gemini without running into the 'not secure' problem

**Comment by iancucatalin1993** [comment]
> I've come across a helpful trick that might save us from the common browser/app security alerts we've been facing. If you sign in to Anthropic claude 2 using your Gmail account first, you can then access Poe or Google Bard/Gemini without running into the 'not secure' problem

Can confirm, this works. 
Btw, usually other apps like GeForce Experience handle this by sending to to a web login while the app listens to the login event.
