### ISSUE TITLE
Unable to Load Perplexity

### ISSUE THREAD

**Issue by stefano-u** [smol-ai/GodMode#203]
Is anyone else unable to load any of the Perplexity data providers?
It just gets stuck on the Cloudflare page:

https://github.com/smol-ai/GodMode/assets/18121592/29baf854-de38-4df3-ae85-fec861753086

**Comment by swyxio** [comment]
loading fine on my end. 
<img width="1360" alt="image" src="https://github.com/smol-ai/GodMode/assets/6764957/205dbbdb-2fec-4b05-a256-895ac1b98c68">

run it locally and see if the devtools show any errors? or try using a VPN, perhaps your IP is tagged by some bot traffic

**Comment by martypenner** [comment]
> Is anyone else unable to load any of the Perplexity data providers?
> It just gets stuck on the Cloudflare page:

Same for me. Devtools and electron logs don't show any notable errors. I can access both of those sites in other browsers on the same machine.

**Comment by swyxio** [comment]
oh dear. why?!??! argh

**Comment by jakkaas** [comment]
Perplexity login issue for me. I am not getting login screen using perplexity. I am using Outlook mail. On restarting, It logs me automatically to Gmail which I don't use (I had created account but don't use)

**Comment by KartikHegde64bit** [comment]
Is there any resolution for this issue? Facing the same in my machine connected to office wifi.
