### ISSUE TITLE
[Bug] Superprompt not being sent to Bing chat automatically

### ISSUE THREAD

**Issue by overcastua** [smol-ai/GodMode#204]
Superprompt is not sent to Bing chat automatically, have to click the send button manually. Works well with the rest providers. I'm using Windows 10

**Comment by swyxio** [comment]
thanks for the note! sometimes we need to update the css selectors.

**Comment by seanoliver** [comment]
Thanks for reporting this @overcastua -- it looks like they changed their dom structure a little but i have a fix here: #208
