### ISSUE TITLE
Latests release GodMode.1.0.0-beta.4 Intel build is actually ARM64

### ISSUE THREAD

**Issue by jimmystridh** [smol-ai/GodMode#205]
I got the GodMode.1.0.0-beta.4.dmg

```
> file GodMode.app/Contents/MacOS/GodMode
GodMode: Mach-O 64-bit executable arm64
```

**Comment by swyxio** [comment]
oy vey - i just uploaded the -universal version which i'm told works for the intel macs - reopen if any further issues? https://github.com/smol-ai/GodMode/releases/tag/v1.0.0-beta.4
