### ISSUE TITLE
Deleting all text inside superprompt doesn't update in subprompts

### ISSUE THREAD

**Issue by 0xAsynchronous** [smol-ai/GodMode#220]
Description: Deleting all text inside superprompt doesn't update in subprompts.

Steps to Reproduce:
1) Launch GodMode
2) Type something into superprompt
3) Select all text with CMD-A
4) Hit backspace

Expected behavior: 
All text is cleared from all subprompts (i.e. ChatGPT)

Actual behavior:
Text remains

Environment: macOS 13.4. GodMode (v1.0.0-beta.5)

**Comment by swyxio** [comment]
yea maybe we just delete this if statement and that should do it

https://github.com/smol-ai/GodMode/blob/09b4767fd8473ef43d9b288d972042534f775c90/src/renderer/layout.tsx#L69
