### ISSUE TITLE
bard google is not working even after login was succesful but showing nothing now on windows beta latest .6 version

### ISSUE THREAD

**Issue by advocatemushtaq** [smol-ai/GodMode#230]
![image](https://github.com/smol-ai/GodMode/assets/143274796/e52c698a-ef6a-4680-82f8-805bfa8da0ea)

**Comment by lgandecki** [comment]
Same here, might take a look at it but no promises

**Comment by swyxio** [comment]
agree its also broken for me. would appreciate help!

**Comment by swyxio** [comment]
duplicate of #225
