### ISSUE TITLE
Not able To Login Using Direct Google Sign-in[Bug] 

### ISSUE THREAD

**Issue by PoorvajHinge** [smol-ai/GodMode#247]
Not able to Direct Login into CHAT-GPT and BARD , I don't know email and password but I have google account whenever I click LOGIN and then i Click Google it shows me Not secure browser error
![image](https://github.com/smol-ai/GodMode/assets/74683290/0539ac4d-b0e6-44df-a872-0dfb2b010964)
![image](https://github.com/smol-ai/GodMode/assets/74683290/0a4d3842-467f-4078-954f-5e1964784976)

**Comment by PoorvajHinge** [comment]
Tried multiple times but failed every time

**Comment by foreverLoveWisdom** [comment]
* Same for me as well. Somehow, when I typed a prompt and then hit `cmd+enter(MacOS)`, it sent the prompts to all of my current chatbot windows except Bard. Then, I logged out of my Google account, logged in again, and encountered this bug 😄

**Comment by johnfelipe** [comment]
Same for me, im trying this and chatall
How can solve that issue for login with my gmail account

**Comment by swyxio** [comment]
ok now it should work! pls reopen if any fruther issues

**Comment by xxnuo** [comment]
The same problem is encountered in the latest version
![图片](https://github.com/smol-ai/GodMode/assets/54252779/e970e0f8-ccbf-46b1-a3c1-1d9e73eae184)
