### ISSUE TITLE
WebAgent Windows *gmail sign in error

### ISSUE THREAD

**Issue by mrki1111** [smol-ai/GodMode#250]
![image](https://github.com/smol-ai/GodMode/assets/130581689/efb21185-7685-45fb-b061-89236cd1d99a)

Regarding any provider, Gmail 3p login provides the same error all round. I am aware windows release is in beta. Anyone successful with Gmail login so far?

Any suggestions on fix?

**Comment by swyxio** [comment]
no sorry but its usually due to an outdated user agent string. ive just fixed ours, please try it again on beta.9!
