### ISSUE TITLE
GPT 4 cannot generate response in website https://smol.ai

### ISSUE THREAD

**Issue by renaldy-therry** [smol-ai/GodMode#257]
![image](https://github.com/smol-ai/GodMode/assets/86903328/f9b51739-a927-4d2b-b444-25bfb7a7959f)
I am trying to generate response in https://smol.ai using gpt-4 and another gpt model but it cannot generate response, only claude model can generate response

**Comment by mikZybien** [comment]
hello guys can you help me to recover my facebook account? thank you

Sent from Yahoo Mail on Android 
 
  On Sat, Sep 30, 2023 at 12:34 PM, Renaldy ***@***.***> wrote:   



I am trying to generate response in https://smol.ai using gpt-4 and another gpt model but it cannot generate response, only claude model can generate response
