### ISSUE TITLE
I'm not able to login to ChatGPT/OpenAI

### ISSUE THREAD

**Issue by theFong** [smol-ai/GodMode#262]
**Describe the bug**
I am not able to login with OpenAI/ChatGPT. I've downloaded the arm zip and moved it into Applications folder then gone into my security settings to whitelist the app.

**Screenshots**
<img width="309" alt="image" src="https://github.com/smol-ai/GodMode/assets/14320477/2af4f276-8ff8-4bd4-bf46-d6319d2f3cce">

**Desktop (please complete the following information):**

- OS:
<img width="456" alt="image" src="https://github.com/smol-ai/GodMode/assets/14320477/33e2d115-6954-44ef-9812-eaf05de656cd">

- GodMode Version: Version 1.0.0-beta.9 (1.0.0-beta.9)

**Comment by ayushkhd** [comment]
+1 - Google doesn't support the browser that's embedded in the app.

**Comment by swyxio** [comment]
it might be the user agent string needs updating again. let me know if you guys can figure it out
