### ISSUE TITLE
[Bug]  White screen

### ISSUE THREAD

**Issue by singularityeight** [smol-ai/GodMode#264]
I removed all active flags and the program stopped working.
How to restore them? Where are logs and configs stored in Linux?
![image](https://github.com/smol-ai/GodMode/assets/79248005/ec3ee18b-5a43-4476-a222-1bc1f0bf7bd2)

**Comment by swyxio** [comment]
hi @debunkt ! same issue and answer as #266 - its an electron update issue i think. would welcome help in debugging as idk how to reproduce
