### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by jorgearone** [smol-ai/GodMode#265]
![Captura](https://github.com/smol-ai/GodMode/assets/48113927/620097e2-ab52-4b55-be86-14596194bdd4)

Hello, apparently there are browser compatibility issues, any ideas, I'm on a windows machine. any idea??

**Comment by vitaliy2034** [comment]
Any solutions or workarounds?(I have the same problem on linux Ubuntu)

**Comment by iot4mb** [comment]
Try to login with google to different website. I got the same response for GPT, but managed to login to Claude. Once you login to some website, you will be logged in for the rest of them automatically.

**Comment by swyxio** [comment]
yup! thank you for that answer @iot4mb
