### ISSUE TITLE
[Bug] ChatGPT doesn't receive the prompt

### ISSUE THREAD

**Issue by joshjacobson** [smol-ai/GodMode#268]
**Describe the bug**
I did my initial download of this, installed and signed in. Everything works perfectly, except that ChatGPT doesn't receive the prompt.

**To Reproduce**
Download, install, sign-in to all services, write prompt, send prompt.

**Expected behavior**
Prompt should show up in ChatGPT window, but it does not.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Sonoma 14.0
- GodMode Version: Version 1.0.0-beta.9 (1.0.0-beta.9)

**Comment by swyxio** [comment]
fixed by #267 it was just a breaking change from openai. should be fixed int he new version im building now
