### ISSUE TITLE
Getting an error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL':

### ISSUE THREAD

**Issue by flyingCodeMonkeys** [smol-ai/GodMode#269]
I am getting an error when trying to run the query. i entered a super query in the message box and it keeps throwing this error:
"Error
Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
Call Stack
 undefined
  Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.:undefined:undefined
"

It does not seem to be querying the chatgpt.

**Comment by swyxio** [comment]
this is an opaque Electron error that just means there was some error executing the custom js we run to sync all the windows. can you please share which chats you had open when this happened?

**Comment by flyingCodeMonkeys** [comment]
> this is an opaque Electron error that just means there was some error executing the custom js we run to sync all the windows. can you please share which chats you had open when this happened?

Yes. Whenever i open the chatgpt and enter the super query in the bottom text area it throws this error now. When i remove the chatgpt i don't get the error. Also when i add the chargpt, the window does not seem to automatically add the text from the super 
Prompt.

**Comment by flyingCodeMonkeys** [comment]
The latest PR-267 appears to have addressed this issue. 
No longer getting the error when submitting queries. and the super query is also automatically filling the chatgpt text prompts.
https://github.com/smol-ai/GodMode/pull/267
Closing the bug.

**Comment by flyingCodeMonkeys** [comment]
The latest PR-267 appears to have addressed this issue.
No longer getting the error when submitting queries. and the super query is also automatically filling the chatgpt text prompts.
https://github.com/smol-ai/GodMode/pull/267
Closing the bug.
