### ISSUE TITLE
[Bug] Not available for Windows

### ISSUE THREAD

**Issue by PoorvajHinge** [smol-ai/GodMode#271]
![image](https://github.com/smol-ai/GodMode/assets/74683290/b45b85c4-ab49-4662-925e-71831613d509)

no exe file is present for download

**Comment by MattStarfield** [comment]
came to say this as well

**Comment by huachuman** [comment]
Still not there?

It says for Windows get the .exe but there is none...

who put those release notes together? ChatGPT?

**Comment by dantosXD** [comment]
Hoping to find out where to download the update for windows.

**Comment by swyxio** [comment]
calm down i just forgot to build one! am on it

**Comment by swyxio** [comment]
its in release 10 now!
