### ISSUE TITLE
[Bug] Super Prompt Not Sending Text to Other Prompts

### ISSUE THREAD

**Issue by jonathancua** [smol-ai/GodMode#272]
Describe the bug
The text is not sent to other prompts when typing on the super prompt.

To Reproduce
https://github.com/smol-ai/GodMode/assets/77296048/4bab1f38-f192-4ae0-84a7-ec41132de9c1

Expected behavior
In previous versions, typing a text on the super prompt was sent to other prompts as well.

Screenshots
n/a

Desktop (please complete the following information):

- OS: MacOS Monterey 12.7
- GodMode Version 0.0.17

Additional context
n/a

**Comment by swyxio** [comment]
this is an old version. update it :) see Releases
