### ISSUE TITLE
[Feature] Screen Real Estate Ideas

### ISSUE THREAD

**Issue by mcavaliere** [smol-ai/GodMode#31]
I'm loving the menu bar, using it daily. Things do get a little cramped on the screen — maybe more so since I have a learning disability - but I'd wager for anyone, since both GPT-n and Bard output walls of content. 

A few ideas that'd help a ton, in no particular order:
1. Manual resizability;
2. Ability to launch smolmenubar in its own window;
3. A full-screen mode.

I particularly like the external window idea since: 
* It also facilitates resizability (`1` above)
* We could manipulate it using window managers (like [Rectangle](https://rectangleapp.com/))

**Comment by swyxio** [comment]
thanks! have you tried resizing with cmd +/- on the more recent versions? its a new feature

same chat in small text

![image](https://github.com/smol-ai/menubar/assets/6764957/edc4a02a-7f9f-431c-977e-7a873ac289dd)

and big text

![image](https://github.com/smol-ai/menubar/assets/6764957/ea7ae64c-3b18-44ca-9652-d0b736a7069b)

and i can move it around with my window manager (i do use Rectangle!)

left

![image](https://github.com/smol-ai/menubar/assets/6764957/00471451-564f-48e6-a1ec-a1fff27db22d)

and right

![image](https://github.com/smol-ai/menubar/assets/6764957/a685b5e4-01d5-47d4-9f9a-4a55b81e1749)

so the main feature that is missing is "detachability" into its own window, which id be happy to take a PR for

**Comment by mcavaliere** [comment]
Oh wow awesome, I didn't even realize there was a resize handle there. This helps a ton! 🎉 

Having an external window would certainly be nice so that we could tab back to this (since it disappears when you tab to another window). But certainly not essential since it's just a shortcut away. 

Thanks for clarifying!

**Comment by swyxio** [comment]
there not just a resize handle for each pane + for the entire window, you can also resize the text as well. its very impt to me!

**Comment by mcavaliere** [comment]
Awesome. Thanks again and keep up the great work on this kickass tool!
