### ISSUE TITLE
clone Superwhisper features

### ISSUE THREAD

**Issue by swyxio** [smol-ai/GodMode#64]
this https://superwhisper.com/

**Comment by ivanleomk** [comment]
Do you have any idea what they're using locally to run the speech transcription? A bit confused how this might be working if the data never leaves the computer itself. 

I imagine we'll need a simply whisper js port which can run in the webview

**Comment by swyxio** [comment]
i dont unfortunately. i think we can package and run whisper.cpp inside of the electron bundle, i just dunno how to do it myet

**Comment by ivanleomk** [comment]
Ok, I'll take a look at it and work off it. whisper.cpp has a wasm implementation using echamscript so if i can figure out how wasm works sometime this week or the next, will take a stab at it.
