### ISSUE TITLE
cmd+k type interface to easily select which providers to use

### ISSUE THREAD

**Issue by fardeem** [smol-ai/GodMode#91]
I find myself having to switch providers a lot. Preplexity/bing/bard when I need search. GPT/Claude for more normal stuff. This will only get more complex over time. 

I'd wanna build a cmd+k type interface that lets you do this easily. Maybe there's an easier way to do this with just a bar at the top that's super slim with checkboxes on the side. If people like this, I can make this pretty quickly.

**Comment by lgandecki** [comment]
Yeah, I was thinking today that it would be great to switch between coding-related side and life-related :) especially since phind.com is done in #87 . I'm not sure what the solution for that would be. some kind of a switch with a keyboard would be nice

**Comment by swyxio** [comment]
@fardeem sorry for delayed response - mind doing a wireframe mock of what this would look like? cant quite see it in my head

**Comment by swyxio** [comment]
isnt that pretty close to the menubar based approach we have today? also does it let us toggle between sets of providers (eg work vs life) quickly? like i am wondering if maybe what we really want is profiles, and each profile has a set list of providers

**Comment by lgandecki** [comment]
I agree with @swyxio, I was thinking something more in lines of profiles. 
It might be an overkill though, for me this is mostly turning the phind off and on. And only because it has a limited number of messages you can send to it, otherwise I probably wouldn't even bother.

**Comment by fardeem** [comment]
Hmmm - switching between providers within the menubar is a little hard because you as soon as you click on a provider, the menu disappears. 

What if we tried something like this where we add a settings icon, and when you click on it, it shows a list of just the providers. That way people can easily turn/on off a bunch of providers at once.

![image](https://github.com/smol-ai/menubar/assets/2018374/98ed3bfa-0753-4bfc-a74b-f19d71d72067)

**Comment by swyxio** [comment]
@fardeem i would be open to that. want to prototype? (doesnt have to look nice, just want to get a feel for the UX)

**Comment by fardeem** [comment]
Yessir will get to it this weekend

**Comment by katzkuma** [comment]
I agree with @fardeem. If there is something like an interface listing all the providers, that will be great and intuitive to modify which provider is going to display or hide.

**Comment by swyxio** [comment]
@fardeem we are actively working on it in #116  - best not to do now until we are done

**Comment by swyxio** [comment]
its implemented now, the UX could be improved but it works

**Comment by fardeem** [comment]
SUPER COOL!
